### ISSUE TITLE
"Require Only App-Extension-Safe API" build setting is set to NO

### ISSUE THREAD

**Issue by nadavhart** [bignerdranch/CoreDataStack#115]
"Require Only App-Extension-Safe API" build setting is set to NO on all targets, which causes Xcode to show a warning - "Linking against a dylib which is not safe for use in application extensions", when CoreDataStack is used as a framework (via Carthage, for example).

**Comment by nadavhart** [comment]
And now, a PR :()

**Comment by rcedwards** [comment]
Added in https://github.com/bignerdranch/CoreDataStack/releases/tag/v1.2.2
