### ISSUE TITLE
Add BNRCoreDataStackConvenienceUpdates to Add Ons wiki page

### ISSUE THREAD

**Issue by darrarski** [bignerdranch/CoreDataStack#122]
As advised in #119 I have created Add On that includes my extensions for convenience managed object updates. Please, include it on [Add Ons](../wiki/Add-Ons) wiki page.

| Name | Repository |
| --- | --- |
| BNRCoreDataStackConvenienceUpdates | [darrarski/BNRCoreDataStackConvenienceUpdates](https://github.com/darrarski/BNRCoreDataStackConvenienceUpdates) |

Brief description is included in the [README.md](https://github.com/darrarski/BNRCoreDataStackConvenienceUpdates/blob/master/README.md) on Add On's repository. There are also tests that demonstrates example usage. Add On integration is handled by Cocoapods.

**Comment by rcedwards** [comment]
Terrific! 

[Added](https://github.com/bignerdranch/CoreDataStack/wiki/Add-Ons)
