### ISSUE TITLE
Add BNRCoreDataStackConvenienceSaves to Add Ons wiki page

### ISSUE THREAD

**Issue by darrarski** [bignerdranch/CoreDataStack#126]
Please, consider adding my Add On to list on [wiki page](../wiki/Add-Ons). It adds convenience extension to `NSManagedObjectContext` that that makes saving contexts easier and more efficient.

| Description | Repository |
| --- | --- |
| `NSManagedObjectContext` convenience extension for saving or rolling back context and performing grouped saves. | [darrarski/BNRCoreDataStackConvenienceSaves](https://github.com/darrarski/BNRCoreDataStackConvenienceSaves) |

Brief description is included in the [README.md](https://github.com/darrarski/BNRCoreDataStackConvenienceSaves/blob/master/README.md) on Add On's repository. There are also tests that demonstrates example usage. Add On integration is handled by Cocoapods.

**Comment by rcedwards** [comment]
👍 [Add Ons](https://github.com/bignerdranch/CoreDataStack/wiki/Add-Ons)
