### ISSUE TITLE
Add support for creating child NSManagedObjectContext in the main queue

### ISSUE THREAD

**Issue by juanuribeo13** [bignerdranch/CoreDataStack#127]
### Feature Request

I would like to have the option to create child contexts in the main queue.

### Additional Context

It would be great if you could create a new child context in the main queue that can be used for example when the user needs to update and _NSManagedObject_. That way if the user decides not to save the changes, you can just get rid of the context and everything will be as before the changes.

**Comment by rcedwards** [comment]
Added in [v1.2.4](https://github.com/bignerdranch/CoreDataStack/releases/tag/v1.2.4)
