### ISSUE TITLE
Question for BatchUpdateRequest.

### ISSUE THREAD

**Issue by alexiosdev** [bignerdranch/CoreDataStack#146]
### Question
Hi, I really enjoy using this framework, but I have something unclear about batch update.

The test project goes here.
[CoreDataTest.zip](https://github.com/bignerdranch/CoreDataStack/files/274085/CoreDataTest.zip)

I have created CoreDataStack in `ViewController.swift` and seed initial data like this.

```Swift
private func seedInitData(stack:CoreDataStack){
        let moc = stack.newChildContext()
        do {
            try moc.performAndWaitOrThrow {
                let books = ["Book 1", "Book 2", "Book3"]
                for bookTitle in books {
                    let book = Book(managedObjectContext: moc)
                    book.title = bookTitle
                    book.isRent = false
                }
                try moc.saveContextAndWait()
            }
        } catch {
            print("Error creating initial data: \(error)")
        }
    }
```

After that did some testing on `testStack()` function in `NewViewController.swift` file.

```Swift
func testStack(){
        let context = stack.newChildContext(concurrencyType: .PrivateQueueConcurrencyType, name: "batchWorker")
        let batchRequest = NSBatchUpdateRequest(entityName: "Book")
        batchRequest.propertiesToUpdate = ["isRent" : true]
        batchRequest.resultType = .UpdatedObjectIDsResultType
        do{
            
            // First, try to fetch all book object from core data.
            let objs = try context.executeFetchRequest(NSFetchRequest(entityName: "Book"))
            print("--------------Book objects before performing batch updates-----------")
            objs.forEach{
                let book = $0 as! Book
                // It should show false
                print("title : \(book.title), Rent = \(book.isRent)")
            }
            let batchResult = try context.executeRequest(batchRequest) as! NSBatchUpdateResult
            let objectIDS = batchResult.result as! [NSManagedObjectID]
            
            print("\n\n--------------After performing batch request & refreshObject-----------")
            objectIDS.forEach{
                let object = context.objectWithID($0) as! Book
                context.refreshObject(object, mergeChanges: false)
                
                // I think this should show true, but showing false now (So not changed)
                print("title : \(object.title), isRent : \(object.isRent)")
            }
        }catch{}
    }
```

####Output Log

```
--------------Book objects before performing batch updates-----------
title : Optional("Book 2"), Rent = Optional(0)
title : Optional("Book 1"), Rent = Optional(0)
title : Optional("Book3"), Rent = Optional(0)


--------------After performing batch request & refreshObject-----------
title : Optional("Book 2"), isRent : Optional(0)
title : Optional("Book 1"), isRent : Optional(0)
title : Optional("Book3"), isRent : Optional(0)
```

I think after batch request is performed, it should show true.  But it's showing false.
Is this right behaviour or did I understand wrong?

It will be appreciated if anyone can help me.

**Comment by alexiosdev** [comment]
In a word, I want to be sure what is the correct usage of Batch Request Operations using BigNerdRanch CoreDataStack.
Anyone can help me really appreciated.

**Comment by rcedwards** [comment]
Hi @alexiosdev last time I attempted to use the `NSBatchUpdateRequest` it would only be performed on an `NSManagedObjectContext` that had a persistent store connected directly to it. i.e. You could not perform batch updates on a child context.

I would guess this is still the case, however this is not documented by Apple.

I'll try to give it a look again in a few days and confirm for sure thats the case.

**Comment by jeremy-w** [comment]
If that bug is still there, we should definitely document it as a warning note on the related methods in CoreDataStack.

**Comment by rcedwards** [comment]
@jeremy-w This doesn't really pertain to any methods in CoreDataStack. This is simply using an `NSBatchUpdateRequest` on a `NSManagedObjectContext`.

**Comment by alexiosdev** [comment]
@rcedwards , Thank you for your time!

**Comment by jeremy-w** [comment]
Maybe a note on `newChildContext()`? It's not our code that's broken, but it's a gotcha we can't fix.

**Comment by alexiosdev** [comment]
Well, I think that's what Apple's Core Data does.
I only had to call `reset()` on `stack.privateQueueContext` and `stack.mainQueueContext` to get changed data.
If you have better idea, I wish you please share with me.
Thanks.
