### ISSUE TITLE
NSPersistentStoreCoordinator options.

### ISSUE THREAD

**Issue by Aranoledur** [bignerdranch/CoreDataStack#161]
Hi again! Want to say that I really like this framework and want to continue to use it without copying source files. But right now I need a way to add some options to persistent store. I need to encrypt my core data using FileProtection: Complete. Or even better: init CoreDataStack with custom NSPersistentStoreCoordinator. I can do it and create Pull request. But do you need this feature in this framework (will you accept PR)? Or maybe this feature has already been implemented and I couldn't find a way to use it?

**Comment by rcedwards** [comment]
Glad to hear you're enjoying the framework.

I'd be open to a PR that expands `setupSQLiteBackedCoordinator` to accept an optional parameter of store options with a default value of nil (i.e. `storeOptions: [NSObject: AnyObject]? = nil`).

Then add that parameter to the 3 functions in CoreDataStack that call `setupSQLiteBackedCoordinator`.

`newBatchOperationContext...`
`constructSQLiteStack...`
`resetStore...`

**Comment by Aranoledur** [comment]
Glad you have appreciated this change. I have made two PR for swift 2.3 and swift 3.0. I decided to make this parameter optional, but default value is stockSQLiteStoreOptions, because if user want to set nil parameters, better to give him this opportunity. 
Will be happy if you check PRs.

**Comment by rcedwards** [comment]
Terrific thanks. It may take us a few days to get our Swift 2.3/Swift 3.0 branches pushed along so bear with us on these PRs.

**Comment by rcedwards** [comment]
@Aranoledur sorry again for the delay on getting 2.3 and 3.0 pushed out. If this issue is something you'd still like to pursue, please feel free to open PRs against `master` for Swift 3.0 and `swift/2.3` for Swift 2.3. Thanks again

**Comment by Aranoledur** [comment]
Hi! Thanks for not forgetting about me.
PR for swift 2.3 #177 
In swift 3.0 CoreDataStack is deprecated, so there is no need in this functionality.
