### ISSUE TITLE
Issue compiling project with BNRCoreDataStack using Xcode 8 - Swift 2.3

### ISSUE THREAD

**Issue by nprof50** [bignerdranch/CoreDataStack#165]
### Question

When I attempt to compile a project with the BNRCoreDataStack pod from the Swift 2.3 branch (Xcode 8), I receive an "undefined symbols for architecture [arm64]" linker error regarding the CoreDataModelable class initiation method. Any clues as to why this might be occurring?

### Output

`Undefined symbols for architecture arm64:
  "(extension in BNRCoreDataStack):BNRCoreDataStack.CoreDataModelable<A where A: __ObjC.NSManagedObject, A: BNRCoreDataStack.CoreDataModelable>.init (managedObjectContext : __ObjC.NSManagedObjectContext) -> A", referenced from:
      Smartech.Battery.init (information : SmartechBluetooth.BatteryInformation, name : Swift.String, insertIntoManagedObjectContext : __ObjC.NSManagedObjectContext) -> Smartech.Battery in Battery.o
ld: symbol(s) not found for architecture arm64`

**Comment by rcedwards** [comment]
Hi,

The Swift 2.3 and Swift 3.0 branches are works in progress and have not been merged to master at this time.

Thanks
