### ISSUE TITLE
performAndWaitOrThrow not accessible

### ISSUE THREAD

**Issue by markkrenek** [bignerdranch/CoreDataStack#171]
Shouldn't performAndWaitOrThrow be marked public? Compiling the legacy example produces this otherwise:

Example/AppDelegate.swift:62:21: 'performAndWaitOrThrow' is inaccessible due to 'internal' protection level

Using Xcode 8.0 (8A218a)

**Comment by rcedwards** [comment]
@markkrenek Correct that should have been marked public. We'll get a fix pushed up shortly.

**Comment by charliepixegon** [comment]
thanks I was wondering the same. Looks like the PR just needs to be accepted?

**Comment by rcedwards** [comment]
This has been merged to master and I'll cut a release tomorrow morning.

**Comment by mikaelbartlett** [comment]
@rcedwards Thanks for great work. Could you publish the release to cocoa pods repo?

Thanks.

**Comment by rcedwards** [comment]
Added in v2.0.2
