### ISSUE TITLE
Linker issue

### ISSUE THREAD

**Issue by mikaelbartlett** [bignerdranch/CoreDataStack#175]
I get following linker issue after upgrading project to Swift 3:

Undefined symbols for architecture x86_64:
  "(extension in BNRCoreDataStack):BNRCoreDataStack.CoreDataModelable<A where A: __ObjC.NSManagedObject, A: BNRCoreDataStack.CoreDataModelable>.init (managedObjectContext : __ObjC.NSManagedObjectContext) -> A", referenced from:

Any suggestions?

**Comment by rcedwards** [comment]
Hi @mikaelbartlett I just created a sample project and linked to the latest version of CoreDataStack (2.0.2) and didn't see any linker issues.

Perhaps this is an issue with the way cocoapods is linking your frameworks. I'm using cocoapods version 1.0.1, maybe give that a shot.

Thanks

**Comment by mikaelbartlett** [comment]
Here's a project to reproduce the issue
[BNRTest.zip](https://github.com/bignerdranch/CoreDataStack/files/553602/BNRTest.zip)
