### ISSUE TITLE
Linker issue

### ISSUE THREAD

**Issue by mikaelbartlett** [bignerdranch/CoreDataStack#176]
Sorry my previous issue was very thin in information.

I've managed to reproduce the issue in the attached project. I'm not sure if the way I used the init method is still valid. The method is marked deprecated for iOS10 but the project I'm on is targeting iOS9. And I get no build errors so it should be fine?

So I might missed something when migrating to the new version? I moved from swift 2 to swift 3. And from CoreDataStack 1.2.5 to 2.0.2.

[BNRTest.zip](https://github.com/bignerdranch/CoreDataStack/files/553928/BNRTest.zip)

**Comment by mikaelbartlett** [comment]
replacing the following line in Contact.swift:

`self.init(managedObjectContext: managedObjectContext)`

with:

`self.init(entity: Contact.entityDescription(in: managedObjectContext), insertInto: managedObjectContext)`

And I don't get any linker error.

**Comment by rcedwards** [comment]
Yeah this is an interesting issue.

It appears at first glance to be a Swift bug.

I discovered that using the initializer directly such as `Contact(managedObjectContext: context)` works fine, but the use within a `convenience` initializer triggers the linker error.

I also discovered that using the initializer within a static function didn't cause an error i.e.
```
    static func from(json: JSON, managedObjectContext: NSManagedObjectContext) -> Contact {
        let contact = Contact(managedObjectContext: managedObjectContext)
        ...
        return contact
    }
```

**Comment by mikaelbartlett** [comment]
Yes that's what I concluded also.

So perhaps close this issue here and I'll see if I can create a minimal sample for the Swift issue tracker.

**Comment by rcedwards** [comment]
Thanks @mikaelbartlett I think that may be best for now.

Sorry you're seeing this issue, best of luck.

**Comment by mikaelbartlett** [comment]
Here's a link to the issue in swift bug tracker: https://bugs.swift.org/browse/SR-3057
