### ISSUE TITLE
Entity name check should not fail because of module name

### ISSUE THREAD

**Issue by rcedwards** [bignerdranch/CoreDataStack#180]
### Feature Request

Make sure the entity name comparison in `EntityMonitor` does not fail as a result of the module name. Utilize `NSClassFromString` to get a string for comparison. 

### Expected behavior

Entity matching class should not fail based on module name when creating an `EntityMonitor`

### Actual behavior

It fails the match and creates a precondition failure.

**Comment by zwaldowski** [comment]
No, it shouldn't — the exporting of class names to Objective-C is an implementation detail and the Swift team recommends not parsing or attempting to demangle it yourself. The assumption made in Obj-C style Core Data code that `entityName == String(className)` simply can't be trusted anymore. IMHO, when I helped @randomstep debug #178, I said `EntityMonitor` should have an initializer more compatible with `CoreDataModelable`, change its generic requirement to `CoreDataModelable`, or use the `NSManagedObjectModel` of the MOC to do a more reliable look-up for the entity name.

**Comment by rcedwards** [comment]
Perhaps I just miss-worded the issue that @randomstep's PR is fulfilling.

This was supposed to just be an issue to track the work @randomstep was creating.

@zwaldowski do you believe his current PR #178 is insufficient?

**Comment by zwaldowski** [comment]
No, PR #178 is fine. `entity.managedObjectClassName` uses the mangling and `NSClassFromString` is free to use implementation details if it wants, and thus both sides of `==` are `AnyClass`. The comparison is safe. It sounded like this issue was describing extra work to be done, because the description above is not describing what was done in the PR. My bad.

**Comment by rcedwards** [comment]
Title and description should be updated to reflect the work now. Thanks

**Comment by rcedwards** [comment]
Fixed in 1.4.0 and 2.1.0
