### ISSUE TITLE
How can i use CoreDataStack in an Objective-C project

### ISSUE THREAD

**Issue by dalufine** [bignerdranch/CoreDataStack#196]
### Question
In **AppDelegate.h**

```objc
#import <UIKit/UIKit.h>
#import <CoreData/CoreData.h>
#import <CoreDataStack/CoreDataStack.h>  //error**

@interface AppDelegate : UIResponder <UIApplicationDelegate>

@property (nonatomic, strong) UIWindow *window;
@property (nonatomic, strong) CoreDataStack *coreDataStack;  //error **
@property (readonly, strong) NSPersistentContainer *persistentContainer;

-(void)saveContext;

@end
````

**Comment by jeremy-w** [comment]
Short answer: You don't.

Marginally longer answer: The Core Data Stack framework provides a more Swifty interface to Core Data. As such, it's not really intended for use from Objective-C.

**NOTE:** The `CoreDataStack` type itself is deprecated in favor of `NSPersistentContainer`.
