### ISSUE TITLE
Xcode 9 support 

### ISSUE THREAD

**Issue by EAmey** [bignerdranch/CoreDataStack#201]
I have integrated the BNRCoreDataStack pod in one of my project which was written with Swift 3.0.
And it builds successfully with Xcode 8.3.2.
But It gives me Swift compile time errors while trying to build with Xcode 9.
So can anyone tell me what is the issue with latest Xcode?

Thanks in advance,
Amey.

**Comment by rcedwards** [comment]
Hi @EAmey Xcode 9 supports only Swift 3.2 and Swift 4.0.

You can run the migration tool on your project to update to the latest versions of Swift and then update your pods to get the latest CoreDataStack and you should be good to go.
