### ISSUE TITLE
crash on update of app from app store

### ISSUE THREAD

**Issue by rbmedpalli** [bignerdranch/CoreDataStack#202]
__First please review our [guide to contributing to the CoreDataStack](https://github.com/bignerdranch/CoreDataStack/tree/master/.github/CONTRIBUTING.md)__

### Feature Request

Auto migration of model version of coredata model is required.

### Question
When i am trying to update old app to newer app getting crashed even if updated to latest model version of coredata ?

### Actual behavior
below warning is came.
CoreData: annotation:  Failed to load optimized model at path ..(filepath)

### Additional Context

_Platform/Use Case/etc._

__Thanks for contributing to the CoreDataStack!__

**Comment by jeremy-w** [comment]
That sounds frustrating! It doesn't sound like it has much to do with CoreDataStack (versus just plain old CoreData), though.

Maybe you could try asking your CoreData question at StackOverflow or at your local CocoaHeads meetup?
