### ISSUE TITLE
Reset sql stack

### ISSUE THREAD

**Issue by bitomule** [bignerdranch/CoreDataStack#32]
I'm using resetSQLiteStore method but when I run any context save after that it crashes saying that there's no persistent coordinator present. Calling resetSQLiteStore and then creating a new stack fixes the problem.

Any ideas?

**Comment by rcedwards** [comment]
@bitomule I will take a look at the issue you are experiencing. 

Was this while using the latest released version? https://github.com/bignerdranch/CoreDataStack/releases/tag/v0.3.1

We are currently working on some improvements to the stack reset that should be cut into a release shortly. This would include a fix to a potential crash in stack reset #22

**Comment by rcedwards** [comment]
@bitomule There was a bug there when recreating the stack after reseting the old store.

There is a PR up now #33 and we'll release a new pod version shortly. Thanks

**Comment by bitomule** [comment]
Great! Thanks! When are you pushing the pods version?

**Comment by bitomule** [comment]
Installed from moc branch and works without issues. Hope it's merged to master and pushed to cocoapods soon.

**Comment by rcedwards** [comment]
Fixed in 1.0.0 #36
