### ISSUE TITLE
Need access to sectionIndexTitlesForTableView and sectionForSectionIndexTitle

### ISSUE THREAD

**Issue by markkrenek** [bignerdranch/CoreDataStack#86]
NSFetchedResultsController provides sectionIndexTitles and sectionIndexTitleForSectionName(). How do we access those when using FetchedResultsController?

**Comment by rcedwards** [comment]
The property `sections` on `FetchedResultsController<T>` will return a collection of `FetchedResultsSectionInfo<T>` which contains this information and [more](http://bignerdranch.github.io/CoreDataStack/Structs/FetchedResultsSectionInfo.html).

For example:

```swift
let sectionOneTitle = fetchedResultsController.sections?.first?.indexTitle
let sectionIndexTitles = fetchedResultsController.sections?.map() { $0.indexTitle ?? "" }
```
