### ISSUE TITLE
CoreDataModelable entityInContext should be public or private?

### ISSUE THREAD

**Issue by markkrenek** [bignerdranch/CoreDataStack#89]
If I embed the CoreDataStack source files directly in my project, I can use CoreDataModelable entityInContext (since it will be defined as internal). But if I embed CoreDataModelable as a framework, entityInContext is not available, since only public functions are available in a framework.

**Comment by rcedwards** [comment]
Agreed. This should have been made either public or private.

It seems to be a valuable enough function to make public. I'll update that and document the function.

**Comment by markkrenek** [comment]
FYI: I stumbled across this function via auto-complete in Xcode. I was trying to create an NSFetchRequest and didn't really know the pattern to use with CoreDataStack. I think I was using entityInContext to get the entity, then grabbing the name out of that. The much simpler solution of course is to use CoreDataModelable.entityName. I no longer am using entityInContext for this purpose.

**Comment by rcedwards** [comment]
@markkrenek Gotcha. The entityInContext func is helpful for creating fetch request as you can see here [fetchRequestForEntity](https://github.com/bignerdranch/CoreDataStack/blob/master/CoreDataStack/CoreDataModelable.swift#L127)

**Comment by rcedwards** [comment]
Included in [v1.1.5](https://github.com/bignerdranch/CoreDataStack/releases/tag/v1.1.5)
