### ISSUE TITLE
FetchedResultsController not receiving updates fromNSBatchDeleteRequest

### ISSUE THREAD

**Issue by mbrucedogs** [bignerdranch/CoreDataStack#93]
Sorry to bother you guys again.  I am having an issue using the NSBatchDeleteRequest object with the CoreDataStack and the FetchedResultsController.

The issue seems to be that the FetchedResultsController doesn't receive the delegate callbacks after the delete occurs?  So none of the UI gets updated removing the items on the screen. I am initializing CoreDataStack with CoreDataStack.constructSQLiteStack so I can see that the database changes are occurring in the table and also you can see in the code below I am printing out how many items are affected.
           
Below is an example of what I am testing against on the BooksTableViewController.  Is there a way to use the NSBatchDeleteRequest to deal with Bulk Deletes or do you have to fetch the items and then delete them 1 at a time with Context.deleteObject(object)?

 let deleteItems = [
                "American Pastoral",
                "An American Tragedy",
                "Animal Farm"
            ]
            
            let request = NSFetchRequest(entityName: Book.entityName)
            request.predicate = NSPredicate(format: "title IN %@", deleteItems)
            
            let del = NSBatchDeleteRequest(fetchRequest:request)
            del.resultType = .ResultTypeCount

            do{
                if let moc = coreDataStack.newBackgroundWorkerMOC(), let batchResult = try moc.executeRequest(del) as? NSBatchDeleteResult{
                if let count = batchResult.result as? Int where count > 0 {
                    print("delete result:\(count)")
                    try moc.saveContextAndWait()
                }
            }
            }catch{
                print(error)
            }

**Comment by rcedwards** [comment]
`NSBatchDeleteRequest` and `NSBatchUpdateRequest` are requests that execute directly on a persistent store rather than within a managed object context. [Whats new in CoreData 2015 WWDC video](https://developer.apple.com/videos/play/wwdc2015-220/?time=894)

You should perform your fetch again after the batch delete completes.

**Comment by mbrucedogs** [comment]
Ok, I am an idiot, I missed that little nugget.  Also thanks for you reply on the Unique Constraints.

**Comment by rcedwards** [comment]
No worries.

Sure thing!

**Comment by NikKovIos** [comment]
Try this: https://stackoverflow.com/a/46140590/5790492
