### ISSUE TITLE
Is there a way to retrieve cacheName from FetchedResultsController?

### ISSUE THREAD

**Issue by markkrenek** [bignerdranch/CoreDataStack#97]

**Comment by rcedwards** [comment]
This has been merged into master in #98 

A release will be tagged and new pod spec every 2 weeks approx.

**Comment by markkrenek** [comment]
That was quick, Thanks.

**Comment by rcedwards** [comment]
Officially added in https://github.com/bignerdranch/CoreDataStack/releases/tag/v1.2.0
